# Copyright Haven Health Passport. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

################################################################################
#
#   Chaincode Lifecycle Management Policies
#
#   Defines the policies and procedures for chaincode lifecycle management
#   including installation, approval, commitment, and upgrades.
#
################################################################################

# Lifecycle Configuration
LifecycleConfiguration:
  # Default Settings
  Defaults:
    SequenceStart: 1
    InitRequired: true
    EndorsementPlugin: "escc"
    ValidationPlugin: "vscc"
    ApprovalTimeout: "168h"  # 7 days
    CommitTimeout: "24h"     # 1 day

  # Organizations involved in lifecycle
  Organizations:
    - Name: "HealthcareProvider1MSP"
      Role: "Approver"
      Weight: 1
    - Name: "HealthcareProvider2MSP"
      Role: "Approver"
      Weight: 1
    - Name: "UNHCROrgMSP"
      Role: "Approver"
      Weight: 2
    - Name: "RefugeeOrgMSP"
      Role: "Approver"
      Weight: 1

################################################################################
# Installation Policies
################################################################################

Installation:
  # Who can install chaincode
  Permissions:
    AllowedRoles:
      - "admin"
      - "peer_admin"
    AllowedOrganizations:
      - "HealthcareProvider1MSP"
      - "HealthcareProvider2MSP"
      - "UNHCROrgMSP"
      - "RefugeeOrgMSP"

  # Pre-installation checks
  PreInstallChecks:
    SecurityScan:
      Required: true
      Tools:
        - "Sonarqube"
        - "Snyk"
        - "OWASP Dependency Check"
      MinSecurityScore: 85

    CodeReview:
      Required: true
      Reviewers: 2
      ApprovalType: "Unanimous"

    Testing:
      UnitTestCoverage: 80
      IntegrationTestsPassed: true
      PerformanceTestsPassed: true

  # Installation process
  Process:
    Steps:
      - "Download chaincode package"
      - "Verify package signature"
      - "Run security scan"
      - "Check dependencies"
      - "Install on peer"
      - "Verify installation"

    Rollback:
      OnFailure: "Automatic"
      RetentionPeriod: "7 days"

################################################################################
# Approval Policies
################################################################################

Approval:
  # Approval requirements
  Requirements:
    DefaultPolicy:
      Type: "MAJORITY"
      Threshold: 0.6  # 60% of organizations

    CriticalChaincodes:
      - "health-records-chaincode"
      - "identity-management-chaincode"
      Policy:
        Type: "SUPER_MAJORITY"
        Threshold: 0.75  # 75% of organizations

    EmergencyApproval:
      Conditions:
        - "Security patch"
        - "Critical bug fix"
      Policy:
        Type: "FAST_TRACK"
        MinApprovers: 2
        Timeout: "6h"

  # Approval process
  Process:
    Workflow:
      - Step: "Review chaincode definition"
        Responsible: "Technical team"
        Duration: "2 days"

      - Step: "Verify endorsement policy"
        Responsible: "Security team"
        Duration: "1 day"

      - Step: "Check private data collections"
        Responsible: "Privacy team"
        Duration: "1 day"

      - Step: "Test on staging network"
        Responsible: "QA team"
        Duration: "2 days"

      - Step: "Final approval vote"
        Responsible: "Organization admins"
        Duration: "1 day"

    ApprovalCriteria:
      - "All security checks passed"
      - "Endorsement policy validated"
      - "Private data collections configured"
      - "Upgrade compatibility confirmed"
      - "Performance benchmarks met"

################################################################################
# Commitment Policies
################################################################################

Commitment:
  # Commit requirements
  Requirements:
    ReadinessCheck:
      MinOrganizationsReady: 0.75  # 75% must be ready
      CheckTimeout: "5m"
      RetryAttempts: 3

    CommitAuthorization:
      RequiredRole: "admin"
      RequiredOrganizations: ["UNHCROrgMSP"]  # At least UNHCR must commit

  # Commit process
  Process:
    PreCommitChecks:
      - "Verify all approvals collected"
      - "Check chaincode installed on sufficient peers"
      - "Validate sequence number"
      - "Ensure no conflicting chaincodes"

    CommitExecution:
      - "Submit commit transaction"
      - "Wait for ordering service"
      - "Verify block creation"
      - "Confirm chaincode activation"

    PostCommitActions:
      - "Update documentation"
      - "Notify all organizations"
      - "Start monitoring"
      - "Schedule first health check"

################################################################################
# Upgrade Policies
################################################################################

Upgrade:
  # Upgrade planning
  Planning:
    MinNotificationPeriod: "14 days"
    TestingPeriod: "7 days"
    RollbackWindow: "48 hours"

    CompatibilityMatrix:
      MajorVersion:
        BackwardCompatible: false
        DataMigrationRequired: true
        ApprovalThreshold: 0.8  # 80% approval needed

      MinorVersion:
        BackwardCompatible: true
        DataMigrationRequired: false
        ApprovalThreshold: 0.6  # 60% approval needed

      PatchVersion:
        BackwardCompatible: true
        DataMigrationRequired: false
        ApprovalThreshold: 0.5  # 50% approval needed

  # Upgrade execution
  Execution:
    Steps:
      - "Announce upgrade schedule"
      - "Deploy to test network"
      - "Run compatibility tests"
      - "Execute data migration (if needed)"
      - "Gradual rollout to production"
      - "Monitor for issues"
      - "Complete rollout or rollback"

    RollbackTriggers:
      - "Performance degradation > 20%"
      - "Error rate > 5%"
      - "Data corruption detected"
      - "Security vulnerability found"

    SuccessCriteria:
      - "All peers running new version"
      - "No transaction failures"
      - "Performance within baseline"
      - "All tests passing"

################################################################################
# Monitoring and Compliance
################################################################################

Monitoring:
  # Lifecycle metrics
  Metrics:
    Installation:
      - "Time to install"
      - "Installation success rate"
      - "Package size"

    Approval:
      - "Time to approval"
      - "Approval participation rate"
      - "Rejection reasons"

    Commitment:
      - "Commit success rate"
      - "Time to activation"
      - "Readiness check failures"

    Upgrade:
      - "Upgrade frequency"
      - "Rollback frequency"
      - "Downtime during upgrade"

  # Compliance tracking
  Compliance:
    AuditLog:
      - "All lifecycle operations"
      - "Approval votes"
      - "Security scan results"
      - "Test results"

    Reporting:
      Frequency: "Monthly"
      Recipients:
        - "Technical governance board"
        - "Security team"
        - "Compliance team"

      Content:
        - "Chaincode inventory"
        - "Version matrix"
        - "Security posture"
        - "Performance metrics"

################################################################################
# Emergency Procedures
################################################################################

EmergencyProcedures:
  # Security incident response
  SecurityIncident:
    ImmediateActions:
      - "Isolate affected chaincode"
      - "Notify security team"
      - "Begin investigation"

    ResponseTeam:
      Lead: "Security Officer"
      Members:
        - "Technical architects"
        - "Organization admins"
        - "External security experts"

    Resolution:
      - "Develop patch"
      - "Fast-track approval"
      - "Emergency deployment"
      - "Post-incident review"

  # Critical bug response
  CriticalBug:
    Severity Levels:
      P0:  # System down
        ResponseTime: "30 minutes"
        ApprovalBypass: true

      P1:  # Major functionality broken
        ResponseTime: "2 hours"
        ApprovalBypass: false
        FastTrack: true

      P2:  # Minor functionality affected
        ResponseTime: "24 hours"
        NormalProcess: true

################################################################################
# Governance
################################################################################

Governance:
  # Lifecycle committee
  Committee:
    Composition:
      - "Representative from each organization"
      - "Technical architect"
      - "Security officer"
      - "Compliance officer"

    Responsibilities:
      - "Review lifecycle policies"
      - "Approve policy changes"
      - "Resolve disputes"
      - "Plan strategic upgrades"

    Meetings:
      Regular: "Monthly"
      Emergency: "As needed"
      Quorum: "60% of members"

  # Policy updates
  PolicyManagement:
    ReviewCycle: "Quarterly"
    ChangeProcess:
      - "Propose change"
      - "Impact assessment"
      - "Committee review"
      - "Organization approval"
      - "Implementation"

    VersionControl:
      Repository: "git"
      ApprovalRequired: true
      ChangeLog: "Mandatory"

# End of Lifecycle Policies
