name: "healthcare-network"
version: "1.0.0"
client:
  organization: Org1
  logging:
    level: info
  cryptoconfig:
    path: ${FABRIC_CFG_PATH}/crypto-config
  credentialStore:
    path: "./credential-store"
    cryptoStore:
      path: "./crypto-store"
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256

channels:
  healthcare-channel:
    orderers:
      - orderer.havenhealthpassport.org
    peers:
      peer0.org1.havenhealthpassport.org:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org1.havenhealthpassport.org:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  Org1:
    mspid: Org1MSP
    cryptoPath: peerOrganizations/org1.havenhealthpassport.org/users/{username}@org1.havenhealthpassport.org/msp
    peers:
      - peer0.org1.havenhealthpassport.org
      - peer1.org1.havenhealthpassport.org
    certificateAuthorities:
      - ca.org1.havenhealthpassport.org

orderers:
  orderer.havenhealthpassport.org:
    url: grpcs://orderer.havenhealthpassport.org:7050
    grpcOptions:
      ssl-target-name-override: orderer.havenhealthpassport.org
      grpc-max-send-message-length: 15728640
    tlsCACerts:
      path: ${FABRIC_CFG_PATH}/crypto-config/ordererOrganizations/havenhealthpassport.org/tlsca/tlsca.havenhealthpassport.org-cert.pem

peers:
  peer0.org1.havenhealthpassport.org:
    url: grpcs://peer0.org1.havenhealthpassport.org:7051
    eventUrl: grpcs://peer0.org1.havenhealthpassport.org:7053
    grpcOptions:
      ssl-target-name-override: peer0.org1.havenhealthpassport.org
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: ${FABRIC_CFG_PATH}/crypto-config/peerOrganizations/org1.havenhealthpassport.org/tlsca/tlsca.org1.havenhealthpassport.org-cert.pem

  peer1.org1.havenhealthpassport.org:
    url: grpcs://peer1.org1.havenhealthpassport.org:8051
    eventUrl: grpcs://peer1.org1.havenhealthpassport.org:8053
    grpcOptions:
      ssl-target-name-override: peer1.org1.havenhealthpassport.org
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: ${FABRIC_CFG_PATH}/crypto-config/peerOrganizations/org1.havenhealthpassport.org/tlsca/tlsca.org1.havenhealthpassport.org-cert.pem

certificateAuthorities:
  ca.org1.havenhealthpassport.org:
    url: https://ca.org1.havenhealthpassport.org:7054
    caName: ca-org1
    tlsCACerts:
      path: ${FABRIC_CFG_PATH}/crypto-config/peerOrganizations/org1.havenhealthpassport.org/ca/ca.org1.havenhealthpassport.org-cert.pem
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw