# Copyright Haven Health Passport. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

################################################################################
#
#   Channel Security Configuration
#
#   Security policies and configurations for channel-level security
#   in the Haven Health Passport blockchain network.
#
################################################################################

# Channel Security Overview
ChannelSecurity:
  Version: "1.0"
  LastUpdated: "2024-01-20"

  # Global Security Settings
  GlobalSettings:
    TLSRequired: true
    MutualTLSRequired: true
    EncryptionAlgorithm: "AES-256-GCM"
    HashingAlgorithm: "SHA-256"
    SignatureAlgorithm: "ECDSA-P256"

################################################################################
# Channel-Specific Security Configurations
################################################################################

Channels:
  # Healthcare Channel Security
  healthcare-channel:
    # Access Control Lists
    ACLs:
      # Resource access controls
      Resources:
        "/health/records/*":
          Policy: "OR('HealthcareProvider1MSP.member', 'HealthcareProvider2MSP.member', 'RefugeeOrgMSP.member')"
          RequireTLS: true
          AuditAccess: true

        "/health/emergency/*":
          Policy: "OR('HealthcareProvider1MSP.member', 'HealthcareProvider2MSP.member', 'RefugeeOrgMSP.member', 'UNHCROrgMSP.member')"
          RequireTLS: true
          BypassConsent: true
          TimeLimit: "72h"

        "/health/sensitive/*":
          Policy: "AND('HealthcareProvider1MSP.member', 'PatientConsent')"
          RequireTLS: true
          RequireMFA: true
          EncryptionLevel: "ENHANCED"

    # Data Isolation
    DataIsolation:
      Enabled: true

      # Private Data Collections
      PrivateCollections:
        - Name: "personalHealthData"
          IsolationLevel: "STRICT"
          AccessPolicy: "Need-to-know"
          PurgePolicy: "Never"

        - Name: "sensitiveRecords"
          IsolationLevel: "ENHANCED"
          AccessPolicy: "Explicit consent"
          PurgePolicy: "After 7 years"

      # Namespace Isolation
      Namespaces:
        - Name: "patient-records"
          Organizations: ["HealthcareProvider1MSP", "HealthcareProvider2MSP"]
          CrossNamespaceAccess: false

        - Name: "refugee-health"
          Organizations: ["RefugeeOrgMSP", "UNHCROrgMSP"]
          CrossNamespaceAccess: true
          CrossNamespacePolicy: "WITH_APPROVAL"

    # Member Policies
    MemberPolicies:
      JoinChannel:
        Policy: "AND('UNHCROrgMSP.admin', 'OrdererOrg.admin')"
        Requirements:
          - "Identity verification complete"
          - "Security audit passed"
          - "Legal agreements signed"

      LeaveChannel:
        Policy: "SELF OR MAJORITY Admins"
        GracePeriod: "30 days"
        DataHandling: "Export and purge"

    # Gossip Protocol Security
    GossipSecurity:
      Enabled: true

      Configuration:
        # Message Authentication
        MessageAuthentication:
          Algorithm: "HMAC-SHA256"
          KeyRotation: "Weekly"
          ReplayProtection: true
          MessageExpiry: "5 minutes"

        # Peer Authentication
        PeerAuthentication:
          RequireTLS: true
          RequireOrgValidation: true
          MaxPeersPerOrg: 10
          BlacklistDuration: "24h"

        # Anti-Amplification
        AntiAmplification:
          MaxMessageSize: "1MB"
          RateLimiting:
            MessagesPerSecond: 100
            BurstSize: 500

          FloodProtection:
            Enabled: true
            Threshold: 1000
            BanDuration: "1h"

      # Leader Election Security
      LeaderElection:
        UseStaticLeader: false
        LeaderHeartbeatTimeout: "10s"
        LeaderAliveThreshold: "10m"

        Security:
          RequireEndorsement: true
          EndorsementPolicy: "MAJORITY peers"
          LeaderRotation: "24h"

    # State Validation
    StateValidation:
      Enabled: true

      ValidationPolicy:
        Type: "ENHANCED"
        RequireMultipleEndorsers: true
        MinEndorsers: 2
        CrossOrgValidation: true

      AntiTampering:
        StateChecksums: true
        MerkleTreeValidation: true
        PeriodicReconciliation: "1h"

        TamperResponse:
          Detection: "Automatic"
          Action: "Isolate and alert"
          Recovery: "From known good peer"

  # Emergency Channel Security
  emergency-channel:
    # Relaxed security for emergency situations
    ACLs:
      Resources:
        "/emergency/access/*":
          Policy: "OR('HealthcareProvider1MSP.member', 'HealthcareProvider2MSP.member', 'RefugeeOrgMSP.member')"
          RequireTLS: true
          EmergencyBypass: true
          AutoExpire: "72h"

    # Emergency Access Audit
    EmergencyAudit:
      Enhanced: true
      RealTime: true

      Notifications:
        - Channel: "audit-emergency"
        - Email: "emergency-audit@haven-health.org"
        - SMS: "EmergencyResponseTeam"

      PostEmergencyReview:
        Required: true
        Timeline: "24h"
        Reviewers: ["Medical Director", "Security Officer", "UNHCR Representative"]

################################################################################
# Event Security
################################################################################

EventSecurity:
  # Event Hub Security
  EventHub:
    Authentication:
      Required: true
      Type: "mTLS"

    Authorization:
      EventFiltering: true
      OrganizationIsolation: true

      Policies:
        BlockEvents: "Channel members only"
        ChaincodeEvents: "Authorized applications"
        PrivateDataEvents: "Data owners only"

    # Event Encryption
    Encryption:
      InTransit: true
      Algorithm: "AES-256-GCM"
      KeyManagement: "Per-session keys"

    # Event Integrity
    Integrity:
      Signing: true
      SignatureAlgorithm: "ECDSA-P256"
      TimestampVerification: true
      SequenceValidation: true

################################################################################
# Anti-Tampering Measures
################################################################################

AntiTampering:
  # Ledger Protection
  LedgerProtection:
    # Hash Chain Validation
    HashChainValidation:
      Enabled: true
      ValidationInterval: "Every block"
      CrossPeerValidation: true

      MismatchHandling:
        Detection: "Automatic"
        Response: "Halt and investigate"
        Recovery: "Consensus-based"

    # Block Signing
    BlockSigning:
      Required: true
      MultiSignature: true
      SignersPerBlock: 3
      SignatureRotation: "Every 1000 blocks"

  # State Database Protection
  StateProtection:
    # Integrity Checks
    IntegrityChecks:
      Frequency: "Continuous"
      Method: "Merkle proof"
      CrossValidation: true

    # Access Controls
    AccessControls:
      DirectDBAccess: "Prohibited"
      APIOnly: true
      AuditAllAccess: true

    # Snapshot Security
    Snapshots:
      Encrypted: true
      Signed: true
      VerificationRequired: true
      RetentionPolicy: "30 days"

################################################################################
# Secure Messaging
################################################################################

SecureMessaging:
  # Message Security
  MessageSecurity:
    # Encryption
    Encryption:
      Required: true
      Algorithm: "AES-256-GCM"
      KeyExchange: "ECDH-P256"
      PerfectForwardSecrecy: true

    # Message Authentication
    Authentication:
      MACAlgorithm: "HMAC-SHA256"
      SignatureRequired: true
      TimestampTolerance: "5 minutes"

    # Anti-Replay
    AntiReplay:
      Enabled: true
      WindowSize: "1000 messages"
      NonceValidation: true
      DuplicateDetection: true

  # Channel Isolation
  ChannelIsolation:
    StrictIsolation: true
    CrossChannelMessaging: "Prohibited"

    Enforcement:
      NetworkLevel: true
      ApplicationLevel: true
      CryptoLevel: true

################################################################################
# Monitoring and Alerting
################################################################################

SecurityMonitoring:
  # Real-time Monitoring
  RealTimeMonitoring:
    Enabled: true

    Metrics:
      - "Failed authentication attempts"
      - "Unusual transaction patterns"
      - "Network anomalies"
      - "Performance degradation"
      - "Security policy violations"

    Thresholds:
      FailedAuth:
        Warning: 5
        Critical: 10
        Action: "Lock account"

      TransactionAnomaly:
        Deviation: "3 sigma"
        Action: "Alert and investigate"

  # Security Alerts
  Alerts:
    Channels:
      - Type: "Email"
        Recipients: ["security@haven-health.org"]
        Priority: ["Critical", "High"]

      - Type: "SMS"
        Recipients: ["SecurityTeam"]
        Priority: ["Critical"]

      - Type: "SIEM"
        Endpoint: "https://siem.haven-health.org/alerts"
        AllPriorities: true

    EscalationPolicy:
      Critical:
        InitialResponse: "15 minutes"
        Escalation: "30 minutes"
        EscalationPath: ["Security Team", "CTO", "CEO"]

################################################################################
# Compliance and Audit
################################################################################

ComplianceAudit:
  # Audit Trail
  AuditTrail:
    Comprehensive: true
    Immutable: true

    CapturedEvents:
      - "All transactions"
      - "Access attempts"
      - "Configuration changes"
      - "Security events"
      - "Administrative actions"

    Storage:
      Location: "Separate audit channel"
      Encryption: true
      Retention: "7 years"
      Backup: "Real-time replication"

  # Compliance Monitoring
  ComplianceMonitoring:
    Standards:
      - "HIPAA"
      - "GDPR"
      - "ISO 27001"

    AutomatedChecks:
      Frequency: "Continuous"
      Reports: "Monthly"
      Violations: "Immediate alert"

# End of Channel Security Configuration
