# Prometheus configuration for Haven Health Passport Orderer Nodes

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'haven-health-orderers'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

# Load rules
rule_files:
  - "orderer_alerts.yml"

# Scrape configurations
scrape_configs:
  # Orderer metrics
  - job_name: 'orderer-nodes'
    scrape_interval: 10s
    metrics_path: '/metrics'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - 'localhost:9443'
        labels:
          orderer: 'orderer1'
          port: '7050'

      - targets:
          - 'localhost:9444'
        labels:
          orderer: 'orderer2'
          port: '8050'
      - targets:
          - 'localhost:9445'
        labels:
          orderer: 'orderer3'
          port: '9050'

      - targets:
          - 'localhost:9446'
        labels:
          orderer: 'orderer4'
          port: '10050'

      - targets:
          - 'localhost:9447'
        labels:
          orderer: 'orderer5'
          port: '11050'

  # Health check endpoints
  - job_name: 'orderer-health'
    scrape_interval: 30s
    metrics_path: '/healthz'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - 'localhost:9443'
          - 'localhost:9444'
          - 'localhost:9445'
          - 'localhost:9446'
          - 'localhost:9447'
