# Channel Restrictions Configuration
# Haven Health Passport - Multi-Channel Security and Resource Management

# Overview
# Channel restrictions control which orderers can service which channels,
# resource allocation per channel, and access control policies

channelRestrictions:
  # Global channel settings
  global:
    # Maximum number of channels per orderer
    maxChannelsPerOrderer: 10

    # Maximum number of total channels in network
    maxTotalChannels: 50

    # Default channel creation policy
    defaultCreationPolicy: "/Channel/Application/Admins"

    # Channel naming restrictions
    naming:
      # Regex pattern for valid channel names
      pattern: "^[a-z][a-z0-9-]{2,63}$"

      # Reserved channel name prefixes
      reservedPrefixes:
        - "system-"
        - "test-"
        - "admin-"

      # Prohibited channel names
      prohibited:
        - "testchainid"
        - "default"
        - "public"
        - "private"

    # Resource limits per channel
    resourceLimits:
      # Maximum storage per channel
      maxStorageGB: 1000

      # Maximum transactions per second
      maxTPS: 1000

      # Maximum organizations per channel
      maxOrganizations: 50

      # Maximum peers per channel
      maxPeers: 200

  # Channel categories with specific restrictions
  channelCategories:
    # System channels (highest privilege)
    system:
      # Channel patterns that match this category
      patterns:
        - "system-*"
        - "orderer-system-channel"

      # Restrictions
      restrictions:
        # Only system admins can create
        creationPolicy: "/Channel/Orderer/Admins"

        # Cannot be deleted
        deletionAllowed: false

        # Limited to specific orderers
        allowedOrderers:
          - "orderer0.haven-health.com"
          - "orderer1.haven-health.com"

        # Resource allocation
        resources:
          priorityClass: "critical"
          guaranteedTPS: 100
          burstTPS: 500
          storageQuota: "100GB"

        # Access control
        access:
          read: ["/Channel/Orderer/Readers"]
          write: ["/Channel/Orderer/Writers"]
          admin: ["/Channel/Orderer/Admins"]

    # Healthcare data channels
    healthcare:
      patterns:
        - "healthcare-*"
        - "patient-*"
        - "provider-*"

      restrictions:
        creationPolicy: "/Channel/Application/HealthcareAdmins"
        deletionAllowed: false  # Due to regulatory requirements

        # All orderers can service healthcare channels
        allowedOrderers: ["*"]

        resources:
          priorityClass: "high"
          guaranteedTPS: 500
          burstTPS: 2000
          storageQuota: "500GB"

        # HIPAA compliance requirements
        compliance:
          encryption: "required"
          auditLogging: "comprehensive"
          dataRetention: "7years"
          accessLogging: true

        access:
          read: ["/Channel/Application/Readers", "/Channel/Application/HealthcareReaders"]
          write: ["/Channel/Application/Writers", "/Channel/Application/HealthcareWriters"]
          admin: ["/Channel/Application/Admins", "/Channel/Application/HealthcareAdmins"]

    # Emergency response channels
    emergency:
      patterns:
        - "emergency-*"
        - "disaster-*"
        - "crisis-*"

      restrictions:
        creationPolicy: "/Channel/Application/EmergencyAdmins"
        deletionAllowed: true  # Can be deleted after emergency

        # High availability orderers only
        allowedOrderers:
          - "orderer0.haven-health.com"
          - "orderer1.haven-health.com"
          - "orderer2.haven-health.com"

        resources:
          priorityClass: "critical"
          guaranteedTPS: 200
          burstTPS: 1000
          storageQuota: "50GB"

          # Special resource reservation
          reservedResources:
            cpu: "20%"
            memory: "20%"
            network: "30%"

        # Reduced restrictions for emergency
        compliance:
          encryption: "optional"  # Speed over security in emergency
          auditLogging: "minimal"
          dataRetention: "30days"

        access:
          read: ["/Channel/Application/EmergencyResponders"]
          write: ["/Channel/Application/EmergencyResponders"]
          admin: ["/Channel/Application/EmergencyAdmins"]

    # Audit and compliance channels
    audit:
      patterns:
        - "audit-*"
        - "compliance-*"
        - "regulatory-*"

      restrictions:
        creationPolicy: "/Channel/Application/ComplianceAdmins"
        deletionAllowed: false  # Regulatory requirement

        # Specific orderers for compliance
        allowedOrderers:
          - "orderer3.haven-health.com"
          - "orderer4.haven-health.com"

        resources:
          priorityClass: "normal"
          guaranteedTPS: 100
          burstTPS: 500
          storageQuota: "2TB"  # Large storage for audit trails

        # Strict compliance settings
        compliance:
          encryption: "required"
          auditLogging: "immutable"
          dataRetention: "10years"
          tamperDetection: true

        access:
          read: ["/Channel/Application/Auditors", "/Channel/Application/Regulators"]
          write: ["/Channel/Application/ComplianceWriters"]
          admin: ["/Channel/Application/ComplianceAdmins"]

    # Research and analytics channels
    research:
      patterns:
        - "research-*"
        - "analytics-*"
        - "study-*"

      restrictions:
        creationPolicy: "/Channel/Application/ResearchAdmins"
        deletionAllowed: true

        allowedOrderers: ["*"]

        resources:
          priorityClass: "low"
          guaranteedTPS: 50
          burstTPS: 200
          storageQuota: "200GB"

        # Privacy-preserving settings
        compliance:
          encryption: "required"
          anonymization: "required"
          aggregationOnly: true
          minimumAggregationSize: 100

        access:
          read: ["/Channel/Application/Researchers"]
          write: ["/Channel/Application/ResearchWriters"]
          admin: ["/Channel/Application/ResearchAdmins"]

  # Orderer-specific restrictions
  ordererRestrictions:
    # Per-orderer channel assignments
    ordererAssignments:
      "orderer0.haven-health.com":
        # Channels this orderer must service
        required: ["system-channel", "healthcare-primary"]

        # Channels this orderer can service
        allowed: ["healthcare-*", "emergency-*", "system-*"]

        # Channels this orderer cannot service
        prohibited: ["test-*", "development-*"]

        # Maximum channels for this orderer
        maxChannels: 10

      "orderer1.haven-health.com":
        required: ["system-channel", "healthcare-primary"]
        allowed: ["healthcare-*", "emergency-*", "system-*"]
        prohibited: ["test-*", "development-*"]
        maxChannels: 10

      "orderer2.haven-health.com":
        required: ["healthcare-secondary"]
        allowed: ["healthcare-*", "emergency-*", "research-*"]
        prohibited: ["system-*", "audit-*"]
        maxChannels: 15

      "orderer3.haven-health.com":
        required: ["audit-primary"]
        allowed: ["audit-*", "compliance-*", "healthcare-*"]
        prohibited: ["emergency-*"]
        maxChannels: 20

      "orderer4.haven-health.com":
        required: ["audit-secondary"]
        allowed: ["audit-*", "compliance-*", "research-*"]
        prohibited: ["emergency-*", "system-*"]
        maxChannels: 20

  # Resource allocation strategies
  resourceAllocation:
    # Quality of Service (QoS) classes
    qosClasses:
      critical:
        # Resource guarantees
        guarantees:
          cpuPercent: 40
          memoryPercent: 40
          diskIOPS: 5000
          networkBandwidthMbps: 1000

        # Burst allowances
        burst:
          cpuMultiplier: 2
          memoryMultiplier: 1.5
          iopsMultiplier: 2
          bandwidthMultiplier: 3

      high:
        guarantees:
          cpuPercent: 30
          memoryPercent: 30
          diskIOPS: 3000
          networkBandwidthMbps: 500

        burst:
          cpuMultiplier: 1.5
          memoryMultiplier: 1.3
          iopsMultiplier: 1.5
          bandwidthMultiplier: 2

      normal:
        guarantees:
          cpuPercent: 20
          memoryPercent: 20
          diskIOPS: 1000
          networkBandwidthMbps: 200

        burst:
          cpuMultiplier: 1.2
          memoryMultiplier: 1.1
          iopsMultiplier: 1.2
          bandwidthMultiplier: 1.5

      low:
        guarantees:
          cpuPercent: 10
          memoryPercent: 10
          diskIOPS: 500
          networkBandwidthMbps: 100

        burst:
          cpuMultiplier: 1
          memoryMultiplier: 1
          iopsMultiplier: 1
          bandwidthMultiplier: 1

    # Dynamic resource adjustment
    dynamicAdjustment:
      enabled: true

      # Adjustment triggers
      triggers:
        # CPU-based triggers
        cpu:
          scaleUpThreshold: 80    # Percentage
          scaleDownThreshold: 20  # Percentage

        # Memory-based triggers
        memory:
          scaleUpThreshold: 75
          scaleDownThreshold: 25

        # Queue depth triggers
        queueDepth:
          scaleUpThreshold: 1000
          scaleDownThreshold: 100

      # Adjustment actions
      actions:
        scaleUp:
          - "increase-resource-allocation"
          - "add-orderer-to-channel"
          - "enable-burst-mode"

        scaleDown:
          - "decrease-resource-allocation"
          - "remove-orderer-from-channel"
          - "disable-burst-mode"

  # Channel lifecycle management
  lifecycle:
    # Channel creation process
    creation:
      # Required approvals
      approvalPolicy: "MAJORITY"

      # Validation steps
      validation:
        - "check-channel-name"
        - "verify-creation-policy"
        - "check-resource-availability"
        - "validate-orderer-assignment"
        - "verify-compliance-requirements"

      # Automatic setup
      autoSetup:
        - "create-genesis-block"
        - "assign-orderers"
        - "setup-monitoring"
        - "configure-backup"
        - "enable-audit-logging"

    # Channel modification
    modification:
      # Allowed modifications
      allowed:
        - "add-organization"
        - "update-policy"
        - "change-resource-allocation"
        - "modify-orderer-assignment"

      # Prohibited modifications
      prohibited:
        - "change-channel-name"
        - "modify-genesis-block"
        - "reduce-compliance-level"

      # Approval requirements
      approvalPolicy: "MAJORITY"

    # Channel deletion
    deletion:
      # Pre-deletion checks
      preChecks:
        - "verify-no-active-transactions"
        - "confirm-data-archived"
        - "validate-compliance-approval"
        - "check-regulatory-clearance"

      # Deletion process
      process:
        - "stop-transaction-processing"
        - "archive-channel-data"
        - "remove-from-orderers"
        - "cleanup-resources"
        - "update-audit-trail"

      # Grace period
      gracePeriod: "30days"

      # Data retention after deletion
      retentionPeriod: "7years"

  # Monitoring and alerting
  monitoring:
    # Metrics per channel
    channelMetrics:
      - name: "TransactionRate"
        unit: "tps"
        aggregation: "average"

      - name: "BlockHeight"
        unit: "count"
        aggregation: "max"

      - name: "StorageUsed"
        unit: "gigabytes"
        aggregation: "sum"

      - name: "OrganizationCount"
        unit: "count"
        aggregation: "current"

      - name: "ResourceUtilization"
        unit: "percentage"
        aggregation: "average"

    # Alerts
    alerts:
      - name: "ChannelQuotaExceeded"
        condition: "StorageUsed > quota * 0.9"
        severity: "WARNING"
        action: "notify-admins"

      - name: "HighTransactionRate"
        condition: "TransactionRate > maxTPS * 0.8"
        severity: "WARNING"
        action: "enable-burst-mode"

      - name: "UnauthorizedChannelAccess"
        condition: "access-violation"
        severity: "CRITICAL"
        action: "block-and-alert"

      - name: "ResourceExhaustion"
        condition: "ResourceUtilization > 90"
        severity: "CRITICAL"
        action: "scale-resources"

  # Security policies
  security:
    # Channel isolation
    isolation:
      # Network isolation
      networkIsolation: true

      # Storage isolation
      storageIsolation: true

      # Process isolation
      processIsolation: false  # Performance trade-off

    # Access control
    accessControl:
      # Default deny policy
      defaultPolicy: "deny"

      # Explicit allow rules required
      requireExplicitAllow: true

      # Regular access review
      accessReviewInterval: "30days"

    # Data protection
    dataProtection:
      # Encryption at rest
      encryptionAtRest: "required"

      # Encryption in transit
      encryptionInTransit: "required"

      # Key rotation
      keyRotationInterval: "90days"

  # Integration with external systems
  integration:
    # Kubernetes integration
    kubernetes:
      # Use K8s namespaces for channel isolation
      useNamespaces: true

      # Resource quotas from K8s
      useResourceQuotas: true

      # Network policies
      useNetworkPolicies: true

    # AWS integration
    aws:
      # Use IAM for access control
      useIAM: true

      # VPC per channel option
      vpcPerChannel: false  # Cost consideration

      # Security groups per channel
      securityGroupPerChannel: true
