"""Voice Interface Module.

This module provides voice interface components for Haven Health Passport,
including command grammar, voice interactions, and interface design.
"""

from .audio_cues import (
    AccessibilityAudioAdapter,
    AudioCharacteristic,
    AudioCue,
    AudioCueContext,
    AudioCueLibrary,
    AudioCueSystem,
    CueCategory,
    CuePriority,
    CueType,
    CueVariation,
    MedicalAudioCues,
    ToneGenerator,
    ToneParameters,
)
from .confirmation_protocols import (
    AccessibleConfirmationManager,
    ConfirmationContext,
    ConfirmationLevel,
    ConfirmationProtocolManager,
    ConfirmationRequest,
    ConfirmationResponse,
    ConfirmationStatus,
    ConfirmationStrategy,
    ConfirmationType,
    MultipleChoiceStrategy,
    NumericCodeStrategy,
    VerbalRepeatStrategy,
    VerbalYesNoStrategy,
)
from .error_correction_flows import (
    AdaptiveErrorCorrection,
    ClarificationStrategy,
    CorrectionFlow,
    CorrectionResult,
    CorrectionStrategy,
    ErrorContext,
    ErrorCorrectionFlowManager,
    ErrorCorrectionStrategy,
    ErrorType,
    GuidedCompletionStrategy,
    RepetitionStrategy,
    SpellingStrategy,
    UserCapability,
)
from .medical_feedback_provider import MedicalFeedbackProvider
from .progressive_disclosure import (
    AccessibilityDisclosureAdapter,
    AdaptiveDisclosureManager,
    DisclosureLevel,
    DisclosureMetrics,
    DisclosureRule,
    Feature,
    FeatureCategory,
    InteractionContext,
    OnboardingFlowManager,
    ProgressiveDisclosureEngine,
    UserProfile,
    VoiceInterfaceAdapter,
)
from .voice_command_grammar import (
    CommandGrammar,
    CommandGrammarEngine,
    CommandParameter,
    CommandPriority,
    CommandType,
    MultilingualGrammarEngine,
    ParameterType,
    ParsedCommand,
)
from .voice_feedback_system import (
    AdaptiveFeedbackGenerator,
    AudioFeedback,
    AudioFormat,
    FeedbackContext,
    FeedbackPriority,
    FeedbackQueueManager,
    FeedbackTemplate,
    FeedbackTemplateLibrary,
    FeedbackType,
    VoiceFeedbackSystem,
    VoiceParameters,
    VoicePersona,
    VoiceSynthesizer,
)
from .voice_navigation_system import (
    NavigationContext,
    NavigationLevel,
    NavigationNode,
    NavigationState,
    VoiceNavigationSystem,
)
from .voice_shortcuts import (
    PersonalizedShortcutEngine,
    ShortcutCategory,
    ShortcutConfig,
    ShortcutEngine,
    ShortcutMatch,
    ShortcutScope,
    VoiceShortcut,
)
from .wake_word_detection import (
    MultilingualWakeWordEngine,
    ProductionPorcupineDetector,
    WakeWord,
    WakeWordConfig,
    WakeWordDetection,
    WakeWordDetector,
    WakeWordEngine,
    WakeWordModel,
    WakeWordStatus,
)

__all__ = [
    # Command Grammar
    "CommandType",
    "CommandPriority",
    "ParameterType",
    "CommandParameter",
    "CommandGrammar",
    "ParsedCommand",
    "CommandGrammarEngine",
    "MultilingualGrammarEngine",
    # Wake Word Detection
    "WakeWordStatus",
    "WakeWordModel",
    "WakeWord",
    "WakeWordDetection",
    "WakeWordConfig",
    "WakeWordDetector",
    "ProductionPorcupineDetector",
    "WakeWordEngine",
    "MultilingualWakeWordEngine",
    # Voice Shortcuts
    "ShortcutCategory",
    "ShortcutScope",
    "VoiceShortcut",
    "ShortcutMatch",
    "ShortcutConfig",
    "ShortcutEngine",
    "PersonalizedShortcutEngine",
    # Confirmation Protocols
    "ConfirmationType",
    "ConfirmationLevel",
    "ConfirmationStatus",
    "ConfirmationContext",
    "ConfirmationRequest",
    "ConfirmationResponse",
    "ConfirmationStrategy",
    "VerbalYesNoStrategy",
    "VerbalRepeatStrategy",
    "NumericCodeStrategy",
    "MultipleChoiceStrategy",
    "ConfirmationProtocolManager",
    "AccessibleConfirmationManager",
    # Error Correction Flows
    "ErrorType",
    "CorrectionStrategy",
    "UserCapability",
    "ErrorContext",
    "CorrectionFlow",
    "CorrectionResult",
    "ErrorCorrectionStrategy",
    "ClarificationStrategy",
    "RepetitionStrategy",
    "SpellingStrategy",
    "GuidedCompletionStrategy",
    "ErrorCorrectionFlowManager",
    "AdaptiveErrorCorrection",
    # Progressive Disclosure
    "DisclosureLevel",
    "FeatureCategory",
    "InteractionContext",
    "Feature",
    "UserProfile",
    "DisclosureRule",
    "ProgressiveDisclosureEngine",
    "AdaptiveDisclosureManager",
    "VoiceInterfaceAdapter",
    "OnboardingFlowManager",
    "AccessibilityDisclosureAdapter",
    "DisclosureMetrics",
    # Voice Feedback System
    "FeedbackType",
    "FeedbackPriority",
    "VoicePersona",
    "AudioFormat",
    "VoiceParameters",
    "FeedbackTemplate",
    "FeedbackContext",
    "AudioFeedback",
    "FeedbackTemplateLibrary",
    "VoiceSynthesizer",
    "AdaptiveFeedbackGenerator",
    "FeedbackQueueManager",
    "VoiceFeedbackSystem",
    "MedicalFeedbackProvider",
    # Audio Cues
    "CueType",
    "CueCategory",
    "CuePriority",
    "AudioCharacteristic",
    "ToneParameters",
    "AudioCue",
    "CueVariation",
    "ToneGenerator",
    "AudioCueLibrary",
    "AccessibilityAudioAdapter",
    "AudioCueContext",
    "AudioCueSystem",
    "MedicalAudioCues",
    # Voice Navigation System
    "NavigationLevel",
    "NavigationContext",
    "NavigationNode",
    "NavigationState",
    "VoiceNavigationSystem",
]
